version:  '3'
services:
  mysql:
    container_name: reversi-db
    image: mysql:8.0.29
    platform: linux/x86_64
    ports:
      - 3321:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: reversi
      MYSQL_USER: reversi
      MYSQL_PASSWORD: password